In [36]:
import datetime
import numpy as np
import pandas as pd
from scipy.stats import chi2_contingency

In [2]:
dtype = {
    "ID": str,
    "age": str,
    "sex": str,
    "city": str,
    "province": str,
    "country": str,
    "latitude": float,
    "longitude": float,
    "geo_resolution": str,
    "date_onset_symptoms": str,
    "date_admission_hospital": str,
    "date_confirmation": str,
    "symptoms": str,
    "lives_in_Wuhan": str,
    "travel_history_dates": str,
    "travel_history_location": str,
    "reported_market_exposure": str,
    "additional_information": str,
    "chronic_disease": str,
    "source": str,
    "sequence_available": str,
    "outcome": str,
    "date_death_or_discharge": str,
    "notes_for_discussion": str,
    "location": str,
    "admin1": str,
    "admin2": str,
    "admin3": str,
    "country_new": str,
    "admin_id": float,
    "data_moderator_initials": str,
    "travel_history_binary": str
}

In [3]:
df: pd.DataFrame = pd.read_csv(
    "./latestdata.csv",
    dtype=dtype,
    # nrows=1000
)
df

,ID,age,sex,city,province,country,latitude,longitude,geo_resolution,date_onset_symptoms,...,date_death_or_discharge,notes_for_discussion,location,admin3,admin2,admin1,country_new,admin_id,data_moderator_initials,travel_history_binary
0,000-1-1,NaN,male,Shek Lei,Hong Kong,China,22.365019,114.133808,point,NaN,...,NaN,NaN,Shek Lei,NaN,NaN,Hong Kong,China,8029.0,NaN,NaN
1,000-1-10,78,male,Vo Euganeo,Veneto,Italy,45.297748,11.658382,point,NaN,...,22.02.2020,NaN,Vo' Euganeo,NaN,NaN,Veneto,Italy,8954.0,NaN,NaN
2,000-1-100,61,female,NaN,NaN,Singapore,1.353460,103.815100,admin0,NaN,...,17.02.2020,NaN,NaN,NaN,NaN,NaN,Singapore,200.0,NaN,NaN
3,000-1-1000,NaN,NaN,Zhengzhou City,Henan,China,34.629310,113.468000,admin2,NaN,...,NaN,NaN,NaN,NaN,Zhengzhou City,Henan,China,10091.0,NaN,NaN
4,000-1-10000,NaN,NaN,Pingxiang City,Jiangxi,China,27.513560,113.902900,admin2,NaN,...,NaN,NaN,NaN,NaN,Pingxiang City,Jiangxi,China,7060.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,000-1-10894,NaN,NaN,Hangzhou City,Zhejiang,China,29.901660,119.471500,admin2,NaN,...,NaN,NaN,NaN,NaN,Hangzhou City,Zhejiang,China,3980.0,NaN,NaN
996,000-1-10895,NaN,NaN,Hangzhou City,Zhejiang,China,29.901660,119.471500,admin2,NaN,...,NaN,NaN,NaN,NaN,Hangzhou City,Zhejiang,China,3980.0,NaN,NaN
997,000-1-10896,NaN,NaN,Hangzhou City,Zhejiang,China,29.901660,119.471500,admin2,NaN,...,NaN,NaN,NaN,NaN,Hangzhou City,Zhejiang,China,3980.0,NaN,NaN
998,000-1-10897,NaN,NaN,Hangzhou City,Zhejiang,China,29.901660,119.471500,admin2,NaN,...,NaN,NaN,NaN,NaN,Hangzhou City,Zhejiang,China,3980.0,NaN,NaN
999,000-1-10898,NaN,NaN,Hangzhou City,Zhejiang,China,29.901660,119.471500,admin2,NaN,...,NaN,NaN,NaN,NaN,Hangzhou City,Zhejiang,China,3980.0,NaN,NaN

In [4]:
df.info(verbose=True, max_cols=307382, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 33 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID                        1000 non-null   object
 1   age                       81 non-null     object
 2   sex                       77 non-null     object
 3   city                      894 non-null    object
 4   province                  988 non-null    object
 5   country                   1000 non-null   object
 6   latitude                  1000 non-null   float64
 7   longitude                 1000 non-null   float64
 8   geo_resolution            1000 non-null   object
 9   date_onset_symptoms       26 non-null     object
 10  date_admission_hospital   28 non-null     object
 11  date_confirmation         1000 non-null   object
 12  symptoms                  14 non-null     object
 13  lives_in_Wuhan            12 non-null     object
 14  travel_history_dates      24 non-null     object
 15  travel_history_location   29 non-null     object
 16  reported_market_exposure  1 non-null      object
 17  additional_information    455 non-null    object
 18  chronic_disease_binary    1000 non-null   bool
 19  chronic_disease           0 non-null      object
 20  source                    999 non-null    object
 21  sequence_available        0 non-null      object
 22  outcome                   11 non-null     object
 23  date_death_or_discharge   10 non-null     object
 24  notes_for_discussion      5 non-null      object
 25  location                  400 non-null    object
 26  admin3                    59 non-null     object
 27  admin2                    513 non-null    object
 28  admin1                    988 non-null    object
 29  country_new               1000 non-null   object
 30  admin_id                  1000 non-null   float64
 31  data_moderator_initials   0 non-null      object
 32  travel_history_binary     0 non-null      object
dtypes: bool(1), float64(3), object(29)
memory usage: 251.1+ KB

In [5]:
# Total of missing values
total_cells = np.prod(df.shape)
total_missing = df.isnull().sum().sum()
# Percentage of missing data
print((total_missing / total_cells) * 100)

55.71515151515152

In [6]:
df = df.drop('latitude', axis=1)

In [7]:
df = df.drop('longitude', axis=1)

In [8]:
df = df.drop('ID', axis=1)

In [9]:
df = df.drop('data_moderator_initials', axis=1)

In [10]:
df = df.drop('source', axis=1)

In [11]:
df = df.drop('notes_for_discussion', axis=1)

In [12]:
df = df.drop('sequence_available', axis=1)

In [13]:
df = df.drop('additional_information', axis=1)

In [14]:
df["outcome"].value_counts()

outcome
discharge                                         9
critical condition, intubated as of 14.02.2020    1
death                                             1
Name: count, dtype: int64

In [15]:
def parse_outcome(outcome):
    if isinstance(outcome, float):
        return "recovered"
    else:
        dead = ["died", "deceased", "death", "dead"]
        hospital = ["receiving treatment", "under treatment", "hospitalized",
                    "symptoms only improved with cough. currently hospitalized for follow-up.",
                    "treated in an intensive care unit (14.02.2020)", "stable condition", "stable",
                    "critical condition, intubated as of 14.02.2020", "severe", "critical condition", "severe illness",
                    "unstable", "migrated", "migrated_other"]
        recovered = ["alive", "discharge", "discharged from hospital", "recovering at home 03.03.2020",
                     "not hospitalized", "released from quarantine", "https://www.mspbs.gov.py/covid-19.php",
                     "discharged"]

        if outcome in dead:
            return "death"
        if outcome in hospital:
            return "hospitalized"
        if outcome in recovered:
            return "recovered"
    return outcome


df["outcome"].apply(parse_outcome).value_counts()

outcome
recovered       998
hospitalized      1
death             1
Name: count, dtype: int64

In [441]:
df["outcome"] = df["outcome"].apply(parse_outcome)

In [16]:
for col in df:
    if df.dtypes[col] == "object":
        df[col] = df[col].str.lower()

In [17]:
# df["sex"] = df["sex"].fillna(df["sex"].mode()[0])

In [18]:
df["country"] = df["country"].fillna(df["country"].mode()[0])

In [19]:
def get_province(row):
    if row["province"].value_counts().empty:
        return float('NaN')
    else:
        return row["province"].value_counts().idxmax()


df["province"] = df["province"].fillna(df.groupby('country').apply(get_province, include_groups=False))

In [20]:
# Clean age field
def age_to_int(age_str):
    if isinstance(age_str, float):
        return None

    if "-" in age_str:
        age_min, age_max = age_str.split("-")
        if age_min == '':
            return int(age_max)
        if age_max == '':
            return int(age_min)
        age_min, age_max = int(age_min), int(age_max)
        return int((age_min + age_max) / 2)

    if "weeks" in age_str:
        return 0

    if "months" in age_str or "month" in age_str:
        num, _ = age_str.split(" ")
        if int(num) < 12:
            return 0
        return int(int(num) / 12)

    if age_str[-1] == "+" or age_str[-1] == "-":
        return int(age_str[:-1])

    return int(float(age_str))


df["age"] = df["age"].apply(age_to_int)
df["age"] = df["age"].fillna(int(df["age"].mean()))

In [21]:
def parse_bool(x):
    return not isinstance(x, float)

In [22]:
df["chronic_disease_binary"] = df["chronic_disease_binary"].apply(parse_bool)

In [23]:
df["asymptomatic"] = df["date_onset_symptoms"].apply(parse_bool)

In [24]:
df["lives_in_Wuhan"] = df["lives_in_Wuhan"].apply(parse_bool)

In [25]:
df["travel_history_binary"] = df["travel_history_binary"].apply(parse_bool)

In [26]:
df["reported_market_exposure"] = df["reported_market_exposure"].apply(parse_bool)

In [27]:
df.info(verbose=True, max_cols=307382, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 26 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       1000 non-null   float64
 1   sex                       77 non-null     object
 2   city                      894 non-null    object
 3   province                  988 non-null    object
 4   country                   1000 non-null   object
 5   geo_resolution            1000 non-null   object
 6   date_onset_symptoms       26 non-null     object
 7   date_admission_hospital   28 non-null     object
 8   date_confirmation         1000 non-null   object
 9   symptoms                  14 non-null     object
 10  lives_in_Wuhan            1000 non-null   bool
 11  travel_history_dates      24 non-null     object
 12  travel_history_location   29 non-null     object
 13  reported_market_exposure  1000 non-null   bool
 14  chronic_disease_binary    1000 non-null   bool
 15  chronic_disease           0 non-null      object
 16  outcome                   11 non-null     object
 17  date_death_or_discharge   10 non-null     object
 18  location                  400 non-null    object
 19  admin3                    59 non-null     object
 20  admin2                    513 non-null    object
 21  admin1                    988 non-null    object
 22  country_new               1000 non-null   object
 23  admin_id                  1000 non-null   float64
 24  travel_history_binary     1000 non-null   bool
 25  asymptomatic              1000 non-null   bool
dtypes: bool(5), float64(2), object(19)
memory usage: 169.1+ KB

In [56]:
df

,age,sex,city,province,country,geo_resolution,date_onset_symptoms,date_admission_hospital,date_confirmation,symptoms,...,date_death_or_discharge,location,admin3,admin2,admin1,country_new,admin_id,travel_history_binary,asymptomatic,days_since_subject_zero
0,44.0,male,shek lei,hong kong,china,point,NaN,NaN,2020-02-14,NaN,...,NaN,shek lei,NaN,NaN,hong kong,china,8029.0,False,False,89
1,78.0,male,vo euganeo,veneto,italy,point,NaN,NaN,2020-02-21,NaN,...,22.02.2020,vo' euganeo,NaN,NaN,veneto,italy,8954.0,False,False,96
2,61.0,female,NaN,NaN,singapore,admin0,NaN,NaN,2020-02-14,NaN,...,17.02.2020,NaN,NaN,NaN,NaN,singapore,200.0,False,False,89
3,44.0,NaN,zhengzhou city,henan,china,admin2,NaN,NaN,2020-01-26,NaN,...,NaN,NaN,NaN,zhengzhou city,henan,china,10091.0,False,False,70
4,44.0,NaN,pingxiang city,jiangxi,china,admin2,NaN,NaN,2020-02-14,NaN,...,NaN,NaN,NaN,pingxiang city,jiangxi,china,7060.0,False,False,89
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,44.0,NaN,hangzhou city,zhejiang,china,admin2,NaN,NaN,2020-02-03,NaN,...,NaN,NaN,NaN,hangzhou city,zhejiang,china,3980.0,False,False,78
996,44.0,NaN,hangzhou city,zhejiang,china,admin2,NaN,NaN,2020-02-03,NaN,...,NaN,NaN,NaN,hangzhou city,zhejiang,china,3980.0,False,False,78
997,44.0,NaN,hangzhou city,zhejiang,china,admin2,NaN,NaN,2020-02-03,NaN,...,NaN,NaN,NaN,hangzhou city,zhejiang,china,3980.0,False,False,78
998,44.0,NaN,hangzhou city,zhejiang,china,admin2,NaN,NaN,2020-02-03,NaN,...,NaN,NaN,NaN,hangzhou city,zhejiang,china,3980.0,False,False,78
999,44.0,NaN,hangzhou city,zhejiang,china,admin2,NaN,NaN,2020-02-03,NaN,...,NaN,NaN,NaN,hangzhou city,zhejiang,china,3980.0,False,False,78

In [33]:
df['date_confirmation'] = pd.to_datetime(df['date_confirmation'], format='%d.%m.%Y')

In [55]:
df['days_since_subject_zero'] = df["date_confirmation"].apply(lambda d: (d - datetime.datetime.strptime("17.11.2019", '%d.%m.%Y')).days)

In [29]:
for col in df:
    print(df[col].value_counts())

age
44.0    922
64.0     10
33.0      5
47.0      4
54.0      3
26.0      3
24.0      3
50.0      2
7.0       2
43.0      2
34.0      2
16.0      2
25.0      2
78.0      2
29.0      2
60.0      2
28.0      2
35.0      2
30.0      2
27.0      2
45.0      1
17.0      1
62.0      1
42.0      1
38.0      1
55.0      1
10.0      1
8.0       1
61.0      1
69.0      1
66.0      1
68.0      1
51.0      1
58.0      1
84.0      1
40.0      1
53.0      1
82.0      1
79.0      1
56.0      1
52.0      1
21.0      1
88.0      1
39.0      1
Name: count, dtype: int64
sex
male      51
female    26
Name: count, dtype: int64
city
yokohama port     371
wenzhou city       82
ningbo city        37
chengdu city       33
xinxiang city      24
                 ...
guangyuan city      1
sanmenxia city      1
dazu district       1
baoshan city        1
shek lei            1
Name: count, Length: 129, dtype: int64
province
kanagawa prefecture    372
zhejiang               163
sichuan                102
henan                   51
shandong                50
jilin                   34
shanghai                28
shaanxi                 25
yunnan                  25
jiangxi                 21
hunan                   21
chongqing               18
shanxi                  18
tokyo                   13
xinjiang                11
ningxia                  8
nonthaburi               7
liaoning                 7
wakayama prefecture      6
qinghai                  2
tianjin                  2
saitama                  1
veneto                   1
texas                    1
hong kong                1
Name: count, dtype: int64
country
china                   587
japan                   392
singapore                 9
thailand                  7
united arab emirates      3
italy                     1
united states             1
Name: count, dtype: int64
geo_resolution
admin2    441
point     400
admin1     99
admin3     53
admin0      7
Name: count, dtype: int64
date_onset_symptoms
05.02.2020    4
07.02.2020    3
08.02.2020    2
01.02.2020    2
09.02.2020    2
04.02.2020    2
28.01.2020    2
30.01.2020    1
14.02.2020    1
11.02.2020    1
03.02.2020    1
10.02.2020    1
02.02.2020    1
04.04.2020    1
21.01.2020    1
12.02.2020    1
Name: count, dtype: int64
date_admission_hospital
14.02.2020    5
05.02.2020    5
10.02.2020    3
12.02.2020    2
15.02.2020    2
08.02.2020    2
07.02.2020    2
09.02.2020    2
04.02.2020    1
30.01.2020    1
17.02.2020    1
13.02.2020    1
26.01.2020    1
Name: count, dtype: int64
date_confirmation
08.02.2020    141
03.02.2020    124
16.02.2020    123
07.02.2020    115
15.02.2020    106
26.01.2020     90
17.02.2020     86
13.02.2020     69
12.02.2020     42
14.02.2020     30
06.02.2020     26
09.02.2020     23
10.02.2020     11
18.02.2020      7
11.02.2020      3
04.02.2020      3
21.02.2020      1
Name: count, dtype: int64
symptoms
cough                                     3
fever                                     2
fever, severe pneumonia                   1
cough, fever, sore throat                 1
cough, fever                              1
dyspnea, fever                            1
cough, difficulty breathing, fever        1
fever (38 ° c)                            1
37.1 ° c, mild coughing                   1
abdominal pain, pulmonary inflammation    1
sore throat                               1
Name: count, dtype: int64
lives_in_Wuhan
False    988
True      12
Name: count, dtype: int64
travel_history_dates
25.01.2020                 3
22.01.2020                 2
31.01.2020                 2
16.01.2020 - 23.02.2020    1
05.02.2020                 1
24.01.2020                 1
21.01.2020                 1
23.01.2020                 1
23.01.2020 - 05.02.2020    1
10.02.2020                 1
07.02.2020                 1
- 07.02.2020               1
30.01.2020                 1
13.02.2020                 1
01.02.2020                 1
18.01.2020                 1
21.01.2020 - 23.01.2020    1
22.01.2020 - 23.01.2020    1
28.01.2020 - 29.01.2020    1
15.01.2020                 1
Name: count, dtype: int64
travel_history_location
wuhan                                                                                                                                               4
china                                                                                                                                               2
henan                                                                                                                                               2
guiyang city, guizhou; wuhan city, hubei; zhaotong city, yunnan                                                                                     1
wuhan city, hubei; guizhou; qujing city, yunnan; suizhou city, hubei; honghe prefecture, yunnan; baoshan city, yunnan; dehong prefecture, yunnan    1
wuhan city, hubei                                                                                                                                   1
wuhan city, hubei; yongzhou city, hunan; guizhou                                                                                                    1
wuhan city, hubei; lijiang city, yunnan                                                                                                             1
shilin yi county, kunming city, yunnan; chuxiong prefecture, yunnan; dali prefecture, yunnan                                                        1
guangzhou city, guangdong                                                                                                                           1
kunming city, yunnan; hunan                                                                                                                         1
huangshi city, hubei; wuhan city, hubei; guiyang city, guizhou                                                                                      1
aichi prefecture                                                                                                                                    1
harbin city, heilongjiang                                                                                                                           1
anhui                                                                                                                                               1
gansu                                                                                                                                               1
qitaihe city, heilongjiang                                                                                                                          1
dunhua city                                                                                                                                         1
meihekou city                                                                                                                                       1
shenyang city, liaoning; tonghua city, jilin                                                                                                        1
beijing, beijing, china                                                                                                                             1
vietnam                                                                                                                                             1
thailand                                                                                                                                            1
wuhan city, hubei; lijiang city, yunnan; dali prefecture, yunnan                                                                                    1
Name: count, dtype: int64
reported_market_exposure
False    999
True       1
Name: count, dtype: int64
chronic_disease_binary
True    1000
Name: count, dtype: int64
Series([], Name: count, dtype: int64)
outcome
discharge                                         9
critical condition, intubated as of 14.02.2020    1
death                                             1
Name: count, dtype: int64
date_death_or_discharge
02.03.2020    2
22.02.2020    1
17.02.2020    1
20.02.2020    1
29.02.2020    1
05.03.2020    1
27.02.2020    1
26.02.2020    1
07.03.2020    1
Name: count, dtype: int64
location
yokohama port                              371
bamrasnaradura hospital                      7
yuasa                                        3
saiseikai arida hospital, yuasa              3
pixel park, jinkai district                  2
dashun community, dongling south street      2
woodlands crescent                           1
lorong 8 toa payoh                           1
ota city                                     1
haneda airport                               1
shek lei                                     1
fernvale road                                1
vo' euganeo                                  1
yokohama                                     1
mei hwan drive                               1
sunac city, shangcheng                       1
aegean bay, oriental plaza                   1
mei ling street                              1
Name: count, dtype: int64
admin3
gongzhuling city      4
yunyang county        3
pudong district       3
nanguan district      3
tongxin county        3
minhang district      2
wanbailin district    2
wuxi county           2
bishan district       2
fengjie county        2
jiading district      2
hechuan district      2
jiangbei district     2
erdao district        2
gejiu city            2
qinshui county        1
chengkou county       1
liangping district    1
fengdu county         1
dazu district         1
tongliang district    1
ji county             1
pingyao county        1
zhenlai county        1
fengxian district     1
yu county             1
yangpu district       1
longshan district     1
changning district    1
xuhui district        1
songjiang district    1
ziyang county         1
chaoyang district     1
tiexi district        1
shuangliao city       1
dongliao county       1
meihekou city         1
tengchong city        1
Name: count, dtype: int64
admin2
wenzhou city     82
ningbo city      37
chengdu city     33
xinxiang city    24
hangzhou city    20
                 ..
mianyang city     1
yangquan city     1
jincheng city     1
zigong city       1
jinzhong city     1
Name: count, Length: 89, dtype: int64
admin1
kanagawa prefecture    372
zhejiang               163
sichuan                102
henan                   51
shandong                50
jilin                   34
shanghai                28
shaanxi                 25
yunnan                  25
jiangxi                 21
hunan                   21
chongqing               18
shanxi                  18
tokyo                   13
xinjiang                11
ningxia hui              8
nonthaburi               7
liaoning                 7
wakayama prefecture      6
qinghai                  2
tianjin                  2
saitama                  1
veneto                   1
texas                    1
hong kong                1
Name: count, dtype: int64
country_new
china                   587
japan                   392
singapore                 9
thailand                  7
united arab emirates      3
italy                     1
united states             1
Name: count, dtype: int64
admin_id
9850.0    371
9195.0     82
808.0      50
6583.0     37
2165.0     33
         ...
1550.0      1
5447.0      1
3977.0      1
3267.0      1
8029.0      1
Name: count, Length: 140, dtype: int64
travel_history_binary
False    1000
Name: count, dtype: int64
asymptomatic
False    974
True      26
Name: count, dtype: int64

In [30]:
def is_correlated(var_name1, var_name2, data_frame: pd.DataFrame):
    try:
        new_frame = data_frame[[var_name1, var_name2]]
        new_frame = new_frame.dropna(how="any", axis=0)
        ct = pd.crosstab(index=new_frame[var_name1], columns=new_frame[var_name2])
        print(ct)
        chi2_res = chi2_contingency(ct, )
        p, x, dof_ = chi2_res[1], "correlated" if chi2_res[1] < 0.05 else "not-correlated", chi2_res[2]
        return p, x, dof_
    except ValueError:
        return 0, "no data", 0

In [31]:
outcome_df = df[df['outcome'].notna()]

In [32]:
corr = [[], []]
to_check = ["sex", "country", "sex", "lives_in_Wuhan", "travel_history_binary"]
for var1 in df:
    if var1 != "ID" and var1 in to_check:
        p_val, correlation, dof = is_correlated(var1, "outcome", outcome_df)
        if correlation == "correlated":
            corr[0].append((p_val, dof, var1))
        else:
            corr[1].append((p_val, dof, var1))
        print("")

corr[0].sort()
corr[1].sort()

print("Correlated")

for ln in corr[0]:
    print(ln)

print("Non-Correlated")

for ln in corr[1]:
    print(ln)

outcome  critical condition, intubated as of 14.02.2020  death  discharge
sex
female                                                0      0          3
male                                                  1      1          6

outcome    critical condition, intubated as of 14.02.2020  death  discharge
country
china                                                   1      0          0
italy                                                   0      1          0
singapore                                               0      0          9

outcome         critical condition, intubated as of 14.02.2020  death  \
lives_in_Wuhan
False                                                        1      1
True                                                         0      0

outcome         discharge
lives_in_Wuhan
False                   7
True                    2

outcome                critical condition, intubated as of 14.02.2020  death  \
travel_history_binary
False                                                               1      1

outcome                discharge
travel_history_binary
False                          9

Correlated
(0.00020042040948294818, 4, 'country')
Non-Correlated
(0.6323366621862497, 2, 'sex')
(0.762155300011572, 2, 'lives_in_Wuhan')
(1.0, 0, 'travel_history_binary')

In [ ]:
outcome_df.head()